version: "3.0"

services:
  app:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY= "NHF*&Cn8^&R&(sd79as6nds87n(^8r9n7r67s8"
